source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CityWeather' do
    pod 'Alamofire', '~> 4.5'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 4.0'
end
